### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by watanabe-masahiro** [watanabe-masahiro/cheavot_arduino#2]
# TODO

敬称略
### cheavotの使い方
- [x]  常設展示などで作成者本人がいないときに「こだわりの動画を用意して」理解してもらうもの
### cheavotを説明するときのこだわり作品
- [x] こだわり作品を何にするか: コナンのこだわり麻酔銃
- [x] こだわりを何にするか: 高速巻き取り機能
- [x] 他の選択肢 2つを何にするか: 腕時計にしか見えない見た目, 麻酔の威力
## プロトタイプ作成
- [x] slackへのnotify (福田)
- [x] notify通知を全員に設定(渡辺)
- [x] 数字のバグ修正(渡辺→福田)
## 発表資料作成
- [x] 流れの確認 (水野)
### ビデオ
- [x] 素案作成(浅井)
- [x] ストーリーの確認(全員)
- [x] 絵コンテ
- [x] 撮影
- [x] 説明などの音声録音
- [ ] 動画作成
### Idea detail
- [x] 素案作成(水野)
- [x] レビュー(全員)
- [x] 修正
### Design Process Reflection
- [x] 素案作成(福田)
- [x] レビュー(全員)
- [x] 修正
### 参考: 大まかな審査基準
1. 共感からユーザー像をうまくとらえているか？
2. そのユーザー像にとって重要な案件か？
3. 最終的なソリューションにインパクトはあるか？
4. 自分たちのデザインプロセスを的確に判断し, 次につなげられる学びを得ているか？
## 発表
- [x] 発表者決定
- [x] 練習(必要?)
## デモ展示
- [x] 必要なもののリストアップ
